web:
    image: brouter-web
    ports:
        - "8083:80"
    volumes:
        - ./data/profiles:/usr/share/nginx/html/profiles
        - ./web/keys.js:/usr/share/nginx/html/keys.js
        - ./web/config.js:/usr/share/nginx/html/config.js
app:
    build: .
    ports:
        - "17777:17777"
    volumes:
        - ./data/profiles:/data/profiles
        - ./data/segments:/data/segments
        - ./data/customprofiles:/data/customprofiles
    environment:
        - REQUEST_TIMEOUT=300
        - JAVA_OPTS=-Xmx128M -Xms128M -Xmn8M -XX:+PrintCommandLineFlags
        - MAX_THREADS=1
