version: '3.7'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 5000
    env_file:
      - ./.env.prod
  docs:
    image: sismics/docs:latest
    container_name: docs
    restart: always
    environment:
      - DOCS_BASE_URL=https://docs.${DOMAINNAME}
    volumes:
      - docs-data:/data
    expose:
      - 8080
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web

volumes:
  static_volume:
  docs-data:
