version: '3.7'

services:
  plagiarism:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
  docs:
    image: sismics/docs:latest
    container_name: docs
    restart: always
    environment:
      - DOCS_BASE_URL=https://docs.${DOMAINNAME}
    volumes:
      - docs-data:/data
    ports:
      - 8080:8080
  tiles:
    image: gravel/tileserver
    command: run
    volumes:
      - openstreetmap-cyclosm-data:/var/lib/postgresql/12/main
    ports:
      - 8081:80

volumes:
  docs-data:
  openstreetmap-cyclosm-data:
    external: true
