version: '3.7'

services:
  plagiarism:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
  docs:
    image: sismics/docs:latest
    container_name: docs
    restart: always
    environment:
      - DOCS_BASE_URL=https://docs.${DOMAINNAME}
    volumes:
      - docs-data:/data
    ports:
      - 8080:8080
  tiles:
    image: gravel/tileserver
    command: run
    volumes:
      - openstreetmap-cyclosm-data:/var/lib/postgresql/12/main
    ports:
      - 8081:80
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./.env.prod

  nextcloud:
    volumes:
      - nextcloud:/var/www/html
    image: nextcloud
    restart: always
    ports:
      - 8082:80
    environment:
      - MYSQL_HOST=db
    env_file:
      - ./.env.prod
    depends_on:
      - db
  brouter-web:
    image: brouter-web
    ports:
        - "8083:80"
    volumes:
        - ./services/web/static/keidel-me/brouter-profiles:/usr/share/nginx/html/profiles
        - ./services/brouter/web/keys.js:/usr/share/nginx/html/keys.js
        - ./services/brouter/web/config.js:/usr/share/nginx/html/config.js
    depends_on:
      - brouter-app
  brouter-app:
    image: brouter-app
    ports:
        - "17777:17777"
    volumes:
        - ./services/web/static/keidel-me/brouter-profiles:/data/profiles
        - ./services/brouter/data/segments:/data/segments
        - ./services/brouter/data/customprofiles:/data/customprofiles
    environment:
        - REQUEST_TIMEOUT=300
        - JAVA_OPTS=-Xmx128M -Xms128M -Xmn8M -XX:+PrintCommandLineFlags
        - MAX_THREADS=1

volumes:
  docs-data:
  openstreetmap-cyclosm-data:
    external: true
  nextcloud:
  db:
