version: '3.7'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
  docs:
    image: sismics/docs:latest
    container_name: docs
    restart: always
    environment:
      - DOCS_BASE_URL=https://docs.${DOMAINNAME}
    volumes:
      - docs-data:/data
    expose:
      - 8080

volumes:
  docs-data:
